# Jekyll!
# Documentation: https://jekyllrb.com/docs/configuration/
# Quick Overview: http://news.humancoders.com/t/developpement/items/11149-jekyll-cheat-sheet
# Jekyll serve commands:
#   Local:   bundle exec jekyll serve --trace --config _config.yml,_config_local.yml
#   Cloud9:  bundle exec jekyll serve --trace --config _config.yml,_config_c9.yml
#   Local dev w/SASS: bundle exec jekyll serve --detach --config _config.yml,_config_local.yml
#                     sass --sourcemap=auto --update --force --watch style/css/_main.scss:_site/style/css/style.css
#                     sass --sourcemap=auto --watch style/css/_main.scss:_site/style/css/style.css

#
#  ██████  ██       ██████  ██████   █████  ██
# ██       ██      ██    ██ ██   ██ ██   ██ ██
# ██   ███ ██      ██    ██ ██████  ███████ ██
# ██    ██ ██      ██    ██ ██   ██ ██   ██ ██
#  ██████  ███████  ██████  ██████  ██   ██ ███████

title: Media Done Right
description: > # this means to ignore newlines until "baseurl:"
  Media Done Right is a web development shop based in Long Beach, CA.
  We specialize in creating custom websites for our clients and doing what it takes to make them happy.
  We design and develop professional websites that provide value.
  We're also passionate about open source software and the liberties it provides our clients.
baseurl: ""                                                                 # the subpath of your site, e.g. /blog
url: "http://mediadoneright.com"                                                     # the base hostname & protocol for your site

collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/
  pages:
    output: true
    permalink: /:title/

# Content Types  (aka Jekyll Collection)
defaults:
  -
    scope:
      type: "posts" # posts was previously `post` in Jekyll 2.2.
      path: "" # an empty string here means all files in the project
      output: true
    values:
      layout: "post"
      excerpt_separator: <!--break-->
      category: blog
      permalink: /:categories/:year/:title/
      paginate_path: "/blog/page:num/"
      author: "Mike Stewart"
  -                                                                             # Collections
    scope:
      type: "pages" # pages was previously `page` in Jekyll 2.2.
      path: ""
    values:
      layout: "page" # overrides previous default layout
      excerpt_separator: <!--break-->
      author: "Media Done Right"
  -
    scope:
      type: "portfolio" # pages was previously `page` in Jekyll 2.2.
      path: ""
    values:
      layout: "page" # overrides previous default layout
      excerpt_separator: <!--break-->
      author: "Media Done Right"
      #last_modified_at: 2017-01-27 09:09:09 -0800
      sitemap: true


#
#  ██████ ██    ██ ███████ ████████  ██████  ███    ███      ██████  ██       ██████  ██████   █████  ██
# ██      ██    ██ ██         ██    ██    ██ ████  ████     ██       ██      ██    ██ ██   ██ ██   ██ ██
# ██      ██    ██ ███████    ██    ██    ██ ██ ████ ██     ██   ███ ██      ██    ██ ██████  ███████ ██
# ██      ██    ██      ██    ██    ██    ██ ██  ██  ██     ██    ██ ██      ██    ██ ██   ██ ██   ██ ██
#  ██████  ██████  ███████    ██     ██████  ██      ██      ██████  ███████  ██████  ██████  ██   ██ ███████


# Plugin config: jekyll-seo-tag
# SEO & Social
# Add metadata tags for search engines and social networks to better index and display your site's content.
# Docs: https://github.com/jekyll/jekyll-seo-tag
webmaster_verifications:
  google: z08mpbqfq2cp4mfuxeOzinIJcSAqhM7lU0z2YMz72U0
  bing:
  alexa:
  yandex:

social:
  name: Media Done Right
  links:
    - https://twitter.com/MediaDoneRight
    - https://www.facebook.com/MediaDoneRight
    - https://plus.google.com/105200184803537891303
    - https://github.com/MediaDoneRight
    - https://instagram.com/MediaDoneRight

google-site-verification: z08mpbqfq2cp4mfuxeOzinIJcSAqhM7lU0z2YMz72U0
twitter:
  username: MediaDoneRight

# custom MDR: Third party
google-analytics: UA-20598699-2
github:   MediaDoneRight
facebook: MediaDoneRight


# Build settings
markdown: kramdown
theme: minima
timezone: America/Los_Angeles                                                   # MDR: (Jekyll built-in. Just not set by default) Values from: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
future: false                                                                   # MDR: Publish posts or collection documents with a future date.

sass:
  sass_dir: style/css
  style:    expanded

stylesheets:                                                                    # MDR: Added to automate loading of css + js
  - name: JQuery mobile css
    source: //ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css
    local:
  - name: JQuery slick css
    source: //cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css
    local:
  - name: Font Awesome 4.7
    source: /style/fonts/font-awesome-4.7.0/css/font-awesome.min.css
    local: true
  - name: local css
    source: /style/css/style.css
    local: true

javascript:
  - name: JQuery
    source: //ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js
    local:
  # - name: JQuery Mobile
  #   source: //ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.js
  #   local:
  # - name: jQuery Slick Slideshow Plugin
  #   source: //cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js
  #   local:
  - name: local site
    source: /style/js/bootstrap.min.js
    local: true
  - name: local site
    source: /style/js/rockon.js
    local: true

#paginate: 2
#
gems:
  - jemoji          # GitHub-flavored emoji
  - jekyll-seo-tag  # Add metadata tags for search engines and social networks to better index and display your site's content.
  - jekyll-feed
  - jekyll-sitemap
#   - jekyll-pagination

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - .git
  - .c9
  - foo
